pipeline
{

agent {
  label 'server1'
}

tools {
  maven 'mymaven'
}

stages{

    stage('build')
    {
        steps {
            sh 'mvn clean package -Dmaven.compiler.source=17 -Dmaven.compiler.target=17'
        }

        post {
        success {
            archiveArtifacts artifacts: '**/target/*.war'
                 }
            }

    }

   

    
}

}